name: Symfony CI
on:
  push:
    branches:
      - main
    paths:
      - "ressources/s5/nassia-ch/projets/ci-cd-symfony/**"
defaults:
  run:
    working-directory: ressources/s5/nassia-ch/projets/ci-cd-symfony
jobs:
  ci-symfony:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: pcov
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-scripts
      - name: Run PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff
      - name: Run PHP lint
        run: find src tests -name "*.php" -exec php -l {} \;
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
      - name: Audit de sécurité
        run: composer audit --format=json --no-interaction
        continue-on-error: true
      - name: Install production dependencies
        run: composer install --no-dev --optimize-autoloader --no-scripts
      - name: Dump environment variables for production
        run: composer dump-env prod
        env:
          APP_ENV: prod
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Install frontend dependencies
        run: php bin/console importmap:install
        continue-on-error: true
      - name: Compile assets
        run: php bin/console asset-map:compile
        continue-on-error: true
      - name: Create artifact archive
        run: tar -czf symfony-artifact-r1.tar.gz . --exclude=.git --exclude=tests --exclude=var/cache
        continue-on-error: true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: symfony-artifact
          path: ressources/s5/nassia-ch/projets/ci-cd-symfony/symfony-artifact-r1.tar.gz
      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "symfony-artifact-r1.tar.gz"
          target: "/tmp/"
          
      - name: Execute deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/my-app
            tar -xzf /tmp/symfony-artifact-r1.tar.gz
            rm /tmp/symfony-artifact-r1.tar.gz
            composer install --no-dev --optimize-autoloader --ignore-platform-reqs
            php bin/console doctrine:migrations:migrate --no-interaction
            php bin/console cache:clear --env=prod
            php bin/console cache:warmup --env=prod
            sudo chown -R www-data:www-data var/
            sudo systemctl restart apache2
