name: Symfony CI
on:
  push:
    branches:
      - main
    paths:
      - "ressources/s5/nassia-ch/projets/ci-cd-symfony/**"
defaults:
  run:
    working-directory: ressources/s5/nassia-ch/projets/ci-cd-symfony
jobs:
  ci-symfony:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: pcov
          
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-scripts
        
      - name: Run PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff
        
      - name: Run PHP lint
        run: find src tests -name "*.php" -exec php -l {} \;
        
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse
        
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml   
        
      - name: Audit de sécurité
        run: composer audit --format=json --no-interaction
        continue-on-error: true

      # Nouvelles étapes pour créer l'artefact
      - name: Install production dependencies
        run: composer install --no-dev --optimize-autoloader --no-scripts
        
      - name: Dump environment variables for production
        run: composer dump-env prod
        env:
          APP_ENV: prod
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          
      - name: Install frontend dependencies
        run: php bin/console importmap:install
        continue-on-error: true
        
      - name: Compile assets
        run: php bin/console asset-map:compile
        continue-on-error: true
        
      - name: Create artifact archive
        run: |
          mkdir -p /tmp/symfony-artifact
          cp -r . /tmp/symfony-artifact/
          rm -rf /tmp/symfony-artifact/.git
          rm -rf /tmp/symfony-artifact/node_modules
          rm -rf /tmp/symfony-artifact/var/cache
          rm -rf /tmp/symfony-artifact/var/log
          rm -rf /tmp/symfony-artifact/tests
          rm -rf /tmp/symfony-artifact/docker
          rm -f /tmp/symfony-artifact/docker-compose.yml
          rm -f /tmp/symfony-artifact/.env
          cd /tmp
          tar -czf symfony-artifact-r1.tar.gz -C symfony-artifact .
          cp symfony-artifact-r1.tar.gz $GITHUB_WORKSPACE/ressources/s5/nassia-ch/projets/ci-cd-symfony/
              
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: symfony-artifact
          path: symfony-artifact-r1.tar.gz
